### ISSUE TITLE
SW can be improved

### ISSUE THREAD

**Issue by j6k4m8** [j6k4m8/cg#10]
[Smith-Waterman](https://github.com/j6k4m8/GenomiK/blob/master/cgg/cmd/align.go#L25) can be improved by passing the cells into a channel for computation, dependent on their north and west neighbors.

**Comment by j6k4m8** [comment]
Turns out that it's slower to pass via channels than to just let it happen single-threaded.

**Comment by mstewa34** [comment]
So much buildup for such a disappointing payoff.

**Comment by j6k4m8** [comment]
For real :( I have another clever idea for doing a row-wise implementation instead of a diagonal, which would be *N* channels instead of *N×M*, so the channel overhead is way lower but the dependencies are trickier...
